class ScalaClasses(object):
    ALGORITHM_TEMPLATE = "AlgorithmTemplate"
    APPEND_LOAD = "AppendLoad"
    DELTA_LAKE_LOAD = "DeltaLakeLoad"
    DELTA_LOAD = "DeltaLoad"
    FIXED_LENGTH_STRING_EXTRACTOR = "FixedLengthStringExtractor"
    FULL_LOAD = "FullLoad"
    FULL_MATERIALIZATION = "FullMaterialization"
    GZIP_DECOMPRESSOR = "GzipDecompressorBytes"
    SQL_RUNNER = "SQLRunner"
    NESTED_FLATTENER = "NestedFlattener"
    QUERY_MATERIALIZATION = "QueryMaterialization"
    RANGE_MATERIALIZATION = "RangeMaterialization"
    TRANSPOSE = "Transpose"
