class ScalaClasses(object):
    APPEND_LOAD = "AppendLoad"
    DELTA_LOAD = "DeltaLoad"
    FIXED_LENGTH_STRING_EXTRACTOR = "FixedLengthStringExtractor"
    ALGORITHM_TEMPLATE = "AlgorithmTemplate"
    FULL_LOAD = "FullLoad"
    GZIP_DECOMPRESSOR = "GzipDecompressorBytes"
    PARTITION_FULL_MATERIALIZATION = "PartitionFullMaterialization"
    PARTITION_QUERY_MATERIALIZATION = "PartitionQueryMaterialization"
    PARTITION_RANGE_MATERIALIZATION = "PartitionRangeMaterialization"
    NESTED_FLATTENER = "NestedFlattener"
